version: "3"

services:
    timescaledb:
        image: timescale/timescaledb-ha:pg16
        environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=test
        ports:
          - 5432:5432
        restart: unless-stopped
        volumes:
          - pgdata:/home/postgres/pgdata/data
        networks:
          - axon
#        volumes:
#
#
    axon-app:
        image: axon-app:${APPTAG}
        entrypoint: [ "bash", "-c", "yarn run dev"]
        build:
          context: ../
          dockerfile: ./docker/app.Dockerfile
        ports:
          - 3001:3001
        restart: always
        networks:
          - axon
#        volumes:


    some-redis:
        image: redis
        ports:
          - 6379:6379
        restart: always
        networks:
          - axon

#        volumes:
#
networks:
  axon:
    # Use a custom driver
    #driver: custom-driver-1
    name: axon-net
volumes:
  pgdata:

